### PR TITLE
week1

### PR DESCRIPTION
**Pull request by Christinaliu0913**
劉怡貞
http://3.27.188.17:8000/api/attractions?page=1
http://3.27.188.17:8000/api/attractions?page=1&keyword=劍潭
http://3.27.188.17:8000/api/attractions?page=1&keyword=北
http://3.27.188.17:8000/api/attraction/10
http://3.27.188.17:8000/api/mrts

### CODE REVIEW

**Comment by Christinaliu0913** [comment]
劉怡貞
http://3.27.188.17:8000/api/attractions?page=1
[http://3.27.188.17:8000/api/attractions?page=1&keyword=劍潭](http://3.27.188.17:8000/api/attractions?page=1&keyword=%E5%8A%8D%E6%BD%AD)
[http://3.27.188.17:8000/api/attractions?page=1&keyword=北](http://3.27.188.17:8000/api/attractions?page=1&keyword=%E5%8C%97)
http://3.27.188.17:8000/api/attraction/10
http://3.27.188.17:8000/api/mrts

**Comment by Christinaliu0913** [comment]
劉怡貞
http://3.27.188.17:8000/api/attractions?page=1
[http://3.27.188.17:8000/api/attractions?page=1&keyword=劍潭](http://3.27.188.17:8000/api/attractions?page=1&keyword=%E5%8A%8D%E6%BD%AD)
[http://3.27.188.17:8000/api/attractions?page=1&keyword=北](http://3.27.188.17:8000/api/attractions?page=1&keyword=%E5%8C%97)
http://3.27.188.17:8000/api/attraction/10
http://3.27.188.17:8000/api/mrts

**Review by cwpeng — CHANGES_REQUESTED** [review]
- Query parameter `page` should start from 0.
- Name of image field is incorrect.

**Comment by Christinaliu0913** [comment]
劉怡貞
http://13.54.202.95:8000/api/attractions?page=1
http://13.54.202.95:8000/api/attractions?page=0&keyword=劍潭
http://13.54.202.95:8000/api/attractions?page=0&keyword=北
http://13.54.202.95:8000/api/attraction/10
http://13.54.202.95:8000/api/mrts

**Review by cwpeng — CHANGES_REQUESTED** [review]
page=0 means first page, page=1 means second page, so that, for example, http://13.54.202.95:8000/api/attractions?page=0 and http://13.54.202.95:8000/api/attractions?page=1 should be different.

**Comment by Christinaliu0913** [comment]
劉怡貞
http://13.54.202.95:8000/api/attractions?page=1
http://13.54.202.95:8000/api/attractions?page=0&keyword=劍潭
http://13.54.202.95:8000/api/attractions?page=0&keyword=北
http://13.54.202.95:8000/api/attraction/10
http://13.54.202.95:8000/api/mrts

再麻煩老師檢查，謝謝

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
